name: Build App Image From Template (Release)
run-name: Build App Image for "${{ github.event.repository.name }}"

on:
  workflow_dispatch:
jobs:
  build-image:
    uses: supervisely-ecosystem/workflows/.github/workflows/build_image_from_template.yml@per-app-dockerimages
    with:
      image_name: "${{ github.event.repository.name }}"
