name: Build App Image From Template (Release)
run-name: Build App Image for "${{ github.event.inputs.image_tag }}"

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Tag to push (e.g. test-123)"
        required: true
        default: "test-manual"
      push_latest:
        description: "Also push the :latest tag"
        required: false
        type: boolean
        default: false

jobs:
  build-image:
    uses: supervisely-ecosystem/workflows/.github/workflows/build_image_from_template.yml@per-app-dockerimages
    secrets:
      DOCKERHUB_USERNAME: "${{ secrets.DOCKERHUB_USERNAME }}"
      DOCKERHUB_TOKEN: "${{ secrets.DOCKERHUB_TOKEN }}"
    with:
      image_tag: "${{ github.event.inputs.image_tag }}"
      push_latest: ${{ inputs.push_latest }}
